// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

// Program otelcorecol is an OpenTelemetry Collector binary.
package main

/*
#include <stdlib.h>
*/
import "C"

import (
	"log"
	"os"
	"plugin"
	"strings"
	"fmt"
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/processor"
	"go.opentelemetry.io/collector/confmap"
	envprovider "go.opentelemetry.io/collector/confmap/provider/envprovider"
	fileprovider "go.opentelemetry.io/collector/confmap/provider/fileprovider"
	httpprovider "go.opentelemetry.io/collector/confmap/provider/httpprovider"
	httpsprovider "go.opentelemetry.io/collector/confmap/provider/httpsprovider"
	yamlprovider "go.opentelemetry.io/collector/confmap/provider/yamlprovider"
	"go.opentelemetry.io/collector/otelcol"
)

func main(){
	os.Args = []string{"otelcorecol", "--config=./test.yaml"}
	Main()
}

//export Main
func Main() {
	MainWithPlugin(nil)
}

//export MainWithPlugin
func MainWithPlugin(pluginPath *C.char) {
	// Set os.Args when called as an exported function
	// This is necessary when called from FFI since the normal main() function doesn't execute
	if len(os.Args) <= 1 || os.Args[0] == "" {
		os.Args = []string{"otelcorecol", "--config=./test.yaml"}
	}
	
	info := component.BuildInfo{
		Command:     "otelcorecol",
		Description: "Local OpenTelemetry Collector binary, testing only.",
		Version:     "0.124.0-dev",
	}

	// Handle plugin loading
	var dprocs []processor.Factory
	if pluginPath != nil {
		pluginPathStr := C.GoString(pluginPath)
		fmt.Printf("TRy this Loading plugin from Rust parameter: %s\n", pluginPathStr)
		
		if pluginPathStr != "" {
			fmt.Printf("Before the plugin module!!! Am I able to open plugin?")
			pg, err := plugin.Open(pluginPathStr)
			if err != nil {
				fmt.Printf("Error opening plugin %s: %v\n", pluginPathStr, err)
				panic(err)
			}
			fmt.Printf("Am I able to open plugin?")

			sym, err := pg.Lookup("NewFactory")
			if err != nil {
				fmt.Printf("Error looking up NewFactory in plugin %s: %v\n", pluginPathStr, err)
				panic(err)
			}
			fmt.Printf("Successfully loaded plugin: %s\n", pluginPathStr)
			dprocs = append(dprocs, sym.(func() processor.Factory)())
		}
	}
	
	// Also check environment variable as fallback
	sharedLibEnv := os.Getenv("OTEL_COLLECTOR_SHARED_LIBRARY")
	fmt.Printf("OTEL_COLLECTOR_SHARED_LIBRARY environment variable: '%s'\n", sharedLibEnv)
	args := strings.Split(sharedLibEnv, ",")
	fmt.Printf("Split args: %v\n", args)
	for _, arg := range args {
		if arg == "" {
			fmt.Printf("Skipping empty arg\n")
			continue
		}
		fmt.Printf("Loading plugin from env var: %s\n", arg)
		pg, err := plugin.Open(arg)
		if err != nil {
			fmt.Printf("Error opening plugin %s: %v\n", arg, err)
			panic(err)
		}
		sym, err := pg.Lookup("NewFactory")
		if err != nil {
			fmt.Printf("Error looking up NewFactory in plugin %s: %v\n", arg, err)
			panic(err)
		}
		fmt.Printf("Successfully loaded plugin: %s\n", arg)
		dprocs = append(dprocs, sym.(func() processor.Factory)())
	}

	staticComponents, saveErr := components(dprocs)

	dynComps := func() (otelcol.Factories, error) {
		return staticComponents, saveErr
	}

	set := otelcol.CollectorSettings{
		BuildInfo: info,
		Factories: dynComps,
		ConfigProviderSettings: otelcol.ConfigProviderSettings{
			ResolverSettings: confmap.ResolverSettings{
				ProviderFactories: []confmap.ProviderFactory{
					envprovider.NewFactory(),
					fileprovider.NewFactory(),
					httpprovider.NewFactory(),
					httpsprovider.NewFactory(),
					yamlprovider.NewFactory(),
				},
			},
		},
		ProviderModules: map[string]string{
			envprovider.NewFactory().Create(confmap.ProviderSettings{}).Scheme():   "go.opentelemetry.io/collector/confmap/provider/envprovider v1.30.0",
			fileprovider.NewFactory().Create(confmap.ProviderSettings{}).Scheme():  "go.opentelemetry.io/collector/confmap/provider/fileprovider v1.30.0",
			httpprovider.NewFactory().Create(confmap.ProviderSettings{}).Scheme():  "go.opentelemetry.io/collector/confmap/provider/httpprovider v1.30.0",
			httpsprovider.NewFactory().Create(confmap.ProviderSettings{}).Scheme(): "go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.30.0",
			yamlprovider.NewFactory().Create(confmap.ProviderSettings{}).Scheme():  "go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.30.0",
		},
		ConverterModules: []string{},
	}

	if err := run(set); err != nil {
		log.Fatal(err)
	}
}

func runInteractive(params otelcol.CollectorSettings) error {
	cmd := otelcol.NewCommand(params)
	if err := cmd.Execute(); err != nil {
		log.Fatalf("collector server run finished with error: %v", err)
	}

	return nil
}
